version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker-mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
  app:
    build:
      context: .
      dockerfile: ./docker-php/Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/var/www/html
      - ./docker-php/php.ini:/usr/local/etc/php/php.ini
  web:
    build:
      context: .
      dockerfile: ./docker-nginx/Dockerfile
    depends_on:
      - app
    links:
      - app
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
  